spring:
  datasource:
    url: jdbc:h2:mem:hotel-reservation-system
    username: dev
    password: dev
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console