spring:
  datasource:
    hikari:
      auto-commit: false
    url: jdbc:h2:mem:hotel_system_reservation_db
    username: dev
    password: dev
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false